#!/usr/bin/env bash

CHECKOUT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
#BASE_16_URI='https://raw.githubusercontent.com/chriskempson/base16-shell/master/scripts'
#BASE_16_THEME='ocean'

ln -sf $CHECKOUT_PATH/bash_aliases ~/.bash_aliases

#wget $BASE_16_URI/base16-$BASE_16_THEME.sh -O ~/.shell_theme.sh

mkdir -p ~/.config
mkdir -p ~/.vim
mkdir -p ~/.vim/colors
ln -sf $CHECKOUT_PATH/vimrc ~/.vimrc
ln -sf $CHECKOUT_PATH/xoria256.vim ~/.vim/colors/xoria256.vim
